### ISSUE TITLE
Cambios solicitados el 13/12

### ISSUE THREAD

**Issue by kev9318** [kev9318/NetLab2017-TP#11]
Cambio 13/12
Agregar un valor hora para los empleados (Editar Crud)
Crear una nueva pantalla que seleccionando, mediante un combo Año y mes, y empleado, muestre
para un mes específico la lista de horas trabajadas y el total a cobrar.
De la siguiente manera :
David Revoledo
01/12 - 8 Hs
02/12 - 4,5 Hs
...

===============
Total a cobrar : X $.

**Comment by kev9318** [comment]
los cambios en la base de datos ya están, ahora se puede pedir lista de entradas y salidas por mes, año y empleado, y el empleado ahora cuenta con su valor horario

**Comment by natsukis** [comment]
Ya esta terminado los cambios en la parte de servicios, los cambios a la bd para listar por mes y año fue muy util.

**Comment by kev9318** [comment]
Ya esta terminado la capa de presentacion de estos cambios. doy por cerrado este issue.
