### ISSUE TITLE
Control y Optimazacion de codigo

### ISSUE THREAD

**Issue by natsukis** [kev9318/NetLab2017-TP#15]
[Capa Servicios]
Procedo a revisar en la capa de servicios posibles errores no vistos, control de excepciones y revisar que se puede optimizar.

**Comment by davidrevoledo** [comment]
@kev9318 https://github.com/kev9318/NetLab2017-TP/blob/master/TP%20WebApp/Services/Operations/EmployeeID.cs#L17

me parece que tomarse la lista entera de empleados para obtner uno solo...

**Comment by natsukis** [comment]
Jaja gracias david por dar un vistazo tan tarde, EmployeeID se creo solo por las dudas que necesitaran para algo el id en presentación cuando comenzamos pero como no tienen ninguna utilidad al final vamos a eliminarla.
