### ISSUE TITLE
Servicios CRUD de Empleados

### ISSUE THREAD

**Issue by kev9318** [kev9318/NetLab2017-TP#2]
-Nombre Requerido (max 50 caracteres)
-Apellido Requerido (max 50 caracteres)
-País (Combo) (requerido)
-Fecha de Ingreso (opcional)
-Turno donde trabaja (requerido)

**Comment by natsukis** [comment]
Aparentemente terminado, falta probarlo y controlar que todo funcione correctamente.

**Comment by natsukis** [comment]
Pedi algunas modificaciones en la bd a kevin y amablemente lo hizo, ya esta terminado.

**Comment by JanileDantas** [comment]
Creado por @natsukis  el método ReadAll, que devuelve la lista de todos los empleados registrados para que se pueda implementar en la capa de presentación el ShowAll del crud de empleados.
