### ISSUE TITLE
Servicios registro de horarios

### ISSUE THREAD

**Issue by kev9318** [kev9318/NetLab2017-TP#4]

**Comment by natsukis** [comment]
En proceso

**Comment by natsukis** [comment]
Terminado, falta probarlo y recibir el feedback si hay que modificar algo o esta bien.

**Comment by JanileDantas** [comment]
Modificaciones hechas por @natsukis en el método Update y Delete, para que deje de buscar en la capa de servicios el nombre del Country y Shift. Pasa el ID de los mismos a la capa de Datos.
