### ISSUE TITLE
Presentacion CRUD empleados

### ISSUE THREAD

**Issue by kev9318** [kev9318/NetLab2017-TP#5]

**Comment by JanileDantas** [comment]
Implementando CRUD de Empleados: 

○ Nombre Requerido (max 50 caracteres)
○ Apellido Requerido (max 50 caracteres)
○ País (Combo) (requerido)
○ Fecha de Ingreso (opcional)
○ Turno donde trabaja (hay 3 turnos Turno Mañ, Tard, Noch) (requerido)

**Comment by JanileDantas** [comment]
- Implementada View Index del EmployeeController:

El usuario al clickear en Employee en el Menu Superior de la pagina inicial es redireccionado a la pagina que lista los empleados existentes.

**Comment by JanileDantas** [comment]
- Implementada View Form del EmployeeController:

El usuario rellena los datos solicitados y al clickear en el botton -Add- la DB se actualiza con el nuevo empleado

**Comment by kev9318** [comment]
En el form para crear empleado no debería haber un campo ID , ya que el mismo es auto generado por la base de datos y tampoco es editable

**Comment by JanileDantas** [comment]
- Implementada View DeleteEmployee del EmployeeController:
El usuario al clickear en el menu superior desplegable /Employee/Delete es redireccionado a la pagina donde le da la opcion de seleccionar el empleado que quiere eliminar. Una vez seleccionado el empleado, se muestra los datos del mismo y al clickear en el boton -Delete- se elimina el usuario de la DB.

**Comment by JanileDantas** [comment]
- Implementada View ModifyEmployee del EmployeeController:
El usuario al clickear en el menu superior desplegable /Employee/Update es redireccionado a la pagina donde le da la opcion de seleccionar el empleado que quiere modificar. Una vez seleccionado el empleado, se muestra los datos del mismo y al clickear en el boton -Modify- se actualiza el usuario en la DB.

**Comment by JanileDantas** [comment]
Crud de Empleados modificado con una nueva propriedad:

○ valor por hora

**Comment by JanileDantas** [comment]
Implementado ModelValidation para el crud de empleados
