### ISSUE TITLE
Estética web con Bootstrap

### ISSUE THREAD

**Issue by kev9318** [kev9318/NetLab2017-TP#8]
-Los botones para guardar/editar un cambio en el formulario deben ser todos azul con
letras blancas
-Los botones para cancelar una acción deben ser blancos con letras negras.
-El color del menú debe ser color azul oscuro con letras blancas.

**Comment by kev9318** [comment]
-Los botones para guardar/editar un cambio en el formulario deben ser todos azul con
letras blancas:

Asignar class = "btn btn-primary" a los botones

-Los botones para cancelar una acción deben ser blancos con letras negras:

Asignar class = "btn btn-default"

-El color del menú debe ser color azul oscuro con letras blancas:

Aca depende si mantienen el navbar que ya esta en Shared, de ser asi en bootstrap.css se deberia cambiar la propiedad background-color de navbar-inverted y la propiedad color de navbar > li > a

**Comment by JanileDantas** [comment]
Estética definida para pagina inicial:
Menú color azul oscuro con letras blancas.

**Comment by kev9318** [comment]
Done

**Comment by JanileDantas** [comment]
Creado el _MenuSuperior como una vista parcial.
